'use client';
import { useState } from 'react';
import { ArrowRight, ChevronDown, Download, Heart, Home as HomeIcon, Menu, MoreHorizontal, Package, Play, Search as SearchIcon, X } from 'lucide-react';
type View='home'|'search'|'packs';
const demoPacks=[{name:'Cobalt Garage Essentials Vol.2',code:'CG',tags:['Samples','Loops'],art:'cobalt'},{name:'Aurora Cinematic Strings Vol.3',code:'AC',tags:['Samples','Loops'],art:'aurora'},{name:'Voidline Neuro Bass Vol.1',code:'VN',tags:['Samples','Loops'],art:'void'},{name:'Prism Future Riddim Vol.2',code:'PF',tags:['Samples','Loops'],art:'prism'},{name:'Ember Drill FM Textures Vol.3',code:'ED',tags:['Samples','Loops'],art:'ember'},{name:'Glasswave Techno Kicks Vol.2',code:'GT',tags:['Samples','Loops'],art:'glass'},{name:'Cinderpath Dark Trap Vol.3',code:'CD',tags:['Samples','Loops'],art:'cinder'},{name:'Driftwood Lo-Fi Keys Vol.3',code:'DL',tags:['Samples','Loops'],art:'drift'},{name:'Kinetic Bass Music Vol.1',code:'KB',tags:['Samples','Loops'],art:'kinetic'},{name:'Paperlight Acoustic Folk Vol.3',code:'PF',tags:['Samples','Loops'],art:'paper'}];
const samples=[{name:'VL_DEEP_140_drone_texture_01.wav',type:'Drone',tag:'Atmosphere',bpm:'140 BPM',key:'C# Min',time:'0:12'},{name:'VL_TOP_90_percussion_loop_18.wav',type:'Percussion',tag:'Loop',bpm:'90 BPM',key:'F Min',time:'0:08'},{name:'VL_BASS_150_sub_one_shot_07.wav',type:'Bass',tag:'One Shot',bpm:'150 BPM',key:'G Min',time:'0:03'}];
const Icon=({name}:{name:string})=>{const common={size:18,strokeWidth:1.7};if(name==='home')return <HomeIcon {...common}/>;if(name==='search')return <SearchIcon {...common}/>;if(name==='pack')return <Package {...common}/>;if(name==='close')return <X {...common}/>;if(name==='menu')return <Menu {...common}/>;if(name==='play')return <Play size={16} fill="currentColor" strokeWidth={0}/>;if(name==='heart')return <Heart {...common}/>;if(name==='download')return <Download {...common}/>;if(name==='more')return <MoreHorizontal {...common}/>;if(name==='arrow')return <ArrowRight {...common}/>;return <ChevronDown {...common}/>};
export default function Home(){const[view,setView]=useState<View>('home');const[menu,setMenu]=useState(false);const nav=(v:View)=>{setView(v);setMenu(false)};return <main className="site"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><aside className={`sidebar ${menu?'open':''}`}><div className="brand"><div className="brand-mark">W</div><div><strong>WAVLIB</strong><small>SOUND LIBRARY</small></div></div><button className="close" onClick={()=>setMenu(false)} aria-label="Close menu"><Icon name="close"/></button><nav><button className={`nav ${view==='home'?'active':''}`} onClick={()=>nav('home')}><Icon name="home"/><span>Home</span></button><button className={`nav ${view==='search'?'active':''}`} onClick={()=>nav('search')}><Icon name="search"/><span>Search</span></button><button className={`nav ${view==='packs'?'active':''}`} onClick={()=>nav('packs')}><Icon name="pack"/><span>Packs</span></button></nav><div className="legal"><span>Terms</span><span>Privacy</span><span>Disclaimer</span><span>Copyright © WAVLIB</span></div></aside><section className="content"><header className="topbar"><button className="menu" onClick={()=>setMenu(true)} aria-label="Open menu"><Icon name="menu"/></button><div className="mobile-brand">WAVLIB</div><div className="breadcrumb">{view==='home'?'Home':view==='search'?'Search':'Packs'}</div><div className="header-search"><Icon name="search"/><input placeholder="Search sounds by genre, mood, instrument, BPM, key..."/><button className="search-submit" aria-label="Search"><Icon name="arrow"/></button></div></header>{view==='home'?<HomeView/>:view==='search'?<SearchView/>:<PacksView/>}</section></main>}
function HomeView(){return <div className="view"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> WAVLIB SOUND LIBRARY</div><h1>Find the right sound.<br/><em>Sound fast.</em></h1><p>Explore a growing library of samples, textures, loops and production-ready sounds.</p></div><div className="stat"><strong>204,519</strong><span>sounds in the library</span></div></section><section className="pack-section"><div className="section-head"><h2>New Packs</h2><button>See all <Icon name="arrow"/></button></div><div className="pack-grid">{demoPacks.slice(0,5).map(p=><PackCard key={p.name}{...p}/>)}</div></section><section className="samples-section"><div className="section-head"><h2>Latest Samples</h2><button>See all <Icon name="arrow"/></button></div><div className="sample-list">{samples.map((s,i)=><SampleRow key={s.name} sample={s} index={i}/>)}</div></section></div>}
function SampleRow({sample,index}:{sample:typeof samples[number],index:number}){return <div className="sample"><button className="sample-play"><Icon name="play"/></button><div className={`waveform wave-${index+1}`}>{Array.from({length:28},(_,i)=><i key={i}/>)}</div><div className="sample-main"><strong>{sample.name}</strong><div className="sample-tags"><span>{sample.type}</span><span>{sample.tag}</span><span>{sample.bpm}</span><span>{sample.key}</span></div></div><span className="sample-duration">{sample.time}</span><button className="sample-icon"><Icon name="heart"/></button><button className="sample-icon"><Icon name="download"/></button><button className="sample-icon"><Icon name="more"/></button></div>}
function PackCard({name,code,tags,art}:{name:string,code:string,tags:string[],art:string}){return <article className={`pack-card art-${art}`}><div className="cover"><span>{code}</span><div className="cover-glow"/></div><div className="pack-info"><h3>{name}</h3><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></div></article>}
function SearchView(){return <div className="view"><div className="page-title"><div><div className="eyebrow">DISCOVER</div><h1>Search sounds</h1><p>Search and filter samples by genre, mood, instrument, BPM and key.</p></div><span className="result-count">204,519 sounds</span></div><div className="search-panel"><div className="filters">{['Genre','Mood','Instrument','BPM','Key'].map(label=><button key={label}>{label}<Icon name="chevron"/></button>)}</div></div><div className="search-results">{samples.map((s,i)=><SampleRow key={s.name} sample={s} index={i}/>)}</div></div>}
function PacksView(){return <div className="view"><div className="page-title"><div><div className="eyebrow">SOUND COLLECTIONS</div><h1>Packs</h1><p>Browse curated sample packs and sound collections.</p></div><span className="result-count">{demoPacks.length} packs</span></div><div className="pack-grid packs-page">{demoPacks.map(p=><PackCard key={p.name}{...p}/>)}</div></div>}
